// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt0_LwByyvTQEKNdVpGaR2iPWdUzddLuc',
    appId: '1:261442641750:web:326be7df1d07821845c0f7',
    messagingSenderId: '261442641750',
    projectId: 'gym-bro-f5dc7',
    authDomain: 'gym-bro-f5dc7.firebaseapp.com',
    databaseURL: 'https://gym-bro-f5dc7-default-rtdb.firebaseio.com',
    storageBucket: 'gym-bro-f5dc7.appspot.com',
    measurementId: 'G-VTLB24GVV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjXMqDiBfzIQ-jOlpgt8bIBMSCN8q15ig',
    appId: '1:261442641750:android:46f665b8ce26f20745c0f7',
    messagingSenderId: '261442641750',
    projectId: 'gym-bro-f5dc7',
    databaseURL: 'https://gym-bro-f5dc7-default-rtdb.firebaseio.com',
    storageBucket: 'gym-bro-f5dc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtbjth665beRFgmQxIKbJNt1FUAMpaOE0',
    appId: '1:261442641750:ios:7d548f0dce0c247145c0f7',
    messagingSenderId: '261442641750',
    projectId: 'gym-bro-f5dc7',
    databaseURL: 'https://gym-bro-f5dc7-default-rtdb.firebaseio.com',
    storageBucket: 'gym-bro-f5dc7.appspot.com',
    iosBundleId: 'com.example.gymBroAlpha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtbjth665beRFgmQxIKbJNt1FUAMpaOE0',
    appId: '1:261442641750:ios:b6733bd249a25c6045c0f7',
    messagingSenderId: '261442641750',
    projectId: 'gym-bro-f5dc7',
    databaseURL: 'https://gym-bro-f5dc7-default-rtdb.firebaseio.com',
    storageBucket: 'gym-bro-f5dc7.appspot.com',
    iosBundleId: 'com.example.gymBroAlpha.RunnerTests',
  );
}
